main: it.loneliness.mc.mobraid.Plugin
name: MobRaid
version: 0.1
api-version: 1.20
depend: [Locale-API, Citizens]
commands:
  mobraid:
    description: Base command for MobRaid plugin
    usage: /<command> <subcommand>
    aliases: [mr]